"""Generate fixed OSQP workspaces for the PX4 FA control allocator."""

import shutil
from pathlib import Path
import numpy as np
import osqp
from scipy import sparse

# defines
FA_FEASIBILITY_TOL = 5.00e-1
FA_MATRIX_TOL = 1.00e-3

def generate_osqp_workspaces(positions, thrusts, KM, CT, repo_root_path, Np=6):
    """
    Generates OSQP workspaces and headers using the provided pre-calculated Allocation Matrix (B).
    """
    # Reconstruct B natively using the incoming physics vectors
    B = np.zeros((6, Np))
    for i in range(Np):
        pos_i = np.array(positions[i])
        thrust_i = np.array(thrusts[i])
        
        # PX4 Vector allocation formula: torque = (pos x thrust) - (KM * axis)
        moment_i = np.cross(pos_i, thrust_i) - KM[i] * thrust_i

        B[0:3, i] = moment_i
        B[3:6, i] = thrust_i

    if np.linalg.matrix_rank(B) < 6:
        raise RuntimeError("The configured PX4 effectiveness matrix does not have at least rank six.")
    
    mu_min = np.zeros(Np)
    mu_max = np.array(CT)
    
    sw = np.array([200.0, 200.0, 100.0, 1.0, 1.0, 3.0])
    Sw = sparse.diags(sw, format="csc")
    Aq = Sw @ sparse.csc_matrix(B)

    mu_initial = 0.5 * mu_max
    control_initial = B @ mu_initial
    b_initial = sw * control_initial

    repo_root = Path(repo_root_path).resolve()
    generated = (repo_root / "src/lib/control_allocation/control_allocation/generated").resolve()

    if generated.exists():
        shutil.rmtree(generated)
    generated.mkdir(parents=True)

    codegen_settings = dict(
        parameters="vectors",
        extension_name=None,
        use_float=True,
        printing_enable=False,
        profiling_enable=False,
        interrupt_enable=False,
        compile=False,
    )

    # CLOSEST ACHIEVABLE CONTROL WORKSPACE
    P_closest_dense = (Aq.T @ Aq).toarray()
    P_closest = sparse.csc_matrix(np.triu(P_closest_dense))
    q_closest = -(Aq.T @ b_initial)

    A_closest = sparse.eye(Np, format="csc")
    l_closest = mu_min.copy()
    u_closest = mu_max.copy()

    closest_solver = osqp.OSQP()
    closest_solver.setup(
        P=P_closest, q=np.asarray(q_closest).reshape(-1), A=A_closest,
        l=l_closest, u=u_closest, verbose=True, warm_starting=True,
        polishing=False, eps_abs=1e-3, eps_rel=1e-3, max_iter=4000,
        rho=0.5, adaptive_rho=False,
    )
    closest_solver.solve()
    closest_solver.codegen(
        str(generated), force_rewrite=True, include_codegen_src=True,
        prefix="fa_closest_", **codegen_settings,
    )

    # MAXIMUM SATURATION-MARGIN WORKSPACE
    actuator_range = mu_max - mu_min
    n_margin = Np + 1

    P_margin = sparse.csc_matrix((n_margin, n_margin))
    q_margin = np.zeros(n_margin)
    q_margin[-1] = -1.0

    A_margin_eq = sparse.hstack([Aq, sparse.csc_matrix((6, 1))], format="csc")
    A_margin_lower = sparse.hstack([-sparse.eye(Np, format="csc"), sparse.csc_matrix(actuator_range.reshape(-1, 1))], format="csc")
    A_margin_upper = sparse.hstack([sparse.eye(Np, format="csc"), sparse.csc_matrix(actuator_range.reshape(-1, 1))], format="csc")
    A_margin_m = sparse.csc_matrix((np.ones(1), ([0], [Np])), shape=(1, n_margin))

    A_margin = sparse.vstack([A_margin_eq, A_margin_lower, A_margin_upper, A_margin_m], format="csc")

    l_margin = np.concatenate([b_initial, -np.inf * np.ones(Np), -np.inf * np.ones(Np), np.array([0.0])])
    u_margin = np.concatenate([b_initial, -mu_min, mu_max, np.array([0.5])])

    margin_solver = osqp.OSQP()
    margin_solver.setup(
        P=P_margin, q=q_margin, A=A_margin, l=l_margin, u=u_margin,
        verbose=True, warm_starting=True, polishing=False, eps_abs=1e-3,
        eps_rel=1e-3, max_iter=4000, rho=1.00e-06, adaptive_rho=False,
    )
    margin_solver.solve()
    margin_solver.codegen(
        str(generated), force_rewrite=True, include_codegen_src=False,
        prefix="fa_margin_", **codegen_settings,
    )

    # SHARED PROBLEM DATA HEADER
    problem_header = generated / "fa_problem_data.h"
    with problem_header.open("w", encoding="utf-8") as f:
        f.write("/* Generated by fa_wrench_codegen.py.*/\n")
        f.write("#ifndef FA_PROBLEM_DATA_H\n#define FA_PROBLEM_DATA_H\n\n")
        f.write('#include "osqp.h"\n\n')
        f.write("#define FA_WRENCH_DIM 6\n")
        f.write(f"#define FA_NP {Np}\n")
        f.write(f"#define FA_MARGIN_CONSTRAINTS {6 + 2 * Np + 1}\n")
        f.write(f"#define FA_FEASIBILITY_TOL ((OSQPFloat){FA_FEASIBILITY_TOL:.2e})\n")
        f.write(f"#define FA_MATRIX_TOL ((OSQPFloat){FA_MATRIX_TOL:.2e})\n\n")

        f.write("static const OSQPFloat FA_B[FA_WRENCH_DIM][FA_NP] = {\n")
        for row in B:
            values = ", ".join(f"(OSQPFloat){x:.17g}" for x in row)
            f.write(f"    {{{values}}},\n")
        f.write("};\n\n")

        values = ", ".join(f"(OSQPFloat){x:.17g}" for x in sw)
        f.write(f"static const OSQPFloat FA_SW[FA_WRENCH_DIM] = {{{values}}};\n")
        values = ", ".join(f"(OSQPFloat){x:.17g}" for x in mu_min)
        f.write(f"static const OSQPFloat FA_MU_MIN[FA_NP] = {{{values}}};\n")
        values = ", ".join(f"(OSQPFloat){x:.17g}" for x in mu_max)
        f.write(f"static const OSQPFloat FA_MU_MAX[FA_NP] = {{{values}}};\n\n")
        f.write("#endif /* FA_PROBLEM_DATA_H */\n")

    print(f"OSQP version: {osqp.__version__}")
    print(f"PX4 effectiveness-matrix rank: {np.linalg.matrix_rank(B)}")
    print(f"Generated workspaces: {generated}")